//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import org.drinkless.tdlib.TdApi

/**
 * emits [UpdateAccentColors] if the list of supported accent colors has changed.
 */
fun TelegramFlow.accentColorsFlow(): Flow<TdApi.UpdateAccentColors> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateProfileAccentColors] if the list of supported accent colors for user profiles has
 * changed.
 */
fun TelegramFlow.profileAccentColorsFlow(): Flow<TdApi.UpdateProfileAccentColors> =
    this.getUpdatesFlowOfType()
