//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlin.IntArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits animationIds [Int[]] if the list of saved animations was updated.
 */
fun TelegramFlow.savedAnimationsFlow(): Flow<IntArray> =
    this.getUpdatesFlowOfType<TdApi.UpdateSavedAnimations>()
    .mapNotNull { it.animationIds }

/**
 * emits [UpdateAnimationSearchParameters] if the parameters of animation search through
 * getOption(&quot;animation_search_bot_username&quot;) bot has changed.
 */
fun TelegramFlow.animationSearchParametersFlow(): Flow<TdApi.UpdateAnimationSearchParameters> =
    this.getUpdatesFlowOfType()
