//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [BasicGroup] if some data of a basic group has changed. This update is guaranteed to come
 * before the basic group identifier is returned to the application.
 */
fun TelegramFlow.basicGroupFlow(): Flow<TdApi.BasicGroup> =
    this.getUpdatesFlowOfType<TdApi.UpdateBasicGroup>()
    .mapNotNull { it.basicGroup }

/**
 * emits [UpdateBasicGroupFullInfo] if some data in basicGroupFullInfo has been changed.
 */
fun TelegramFlow.basicGroupFullInfoFlow(): Flow<TdApi.UpdateBasicGroupFullInfo> =
    this.getUpdatesFlowOfType()
