//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [Call] if new call was created or information about a call was updated.
 */
fun TelegramFlow.callFlow(): Flow<TdApi.Call> = this.getUpdatesFlowOfType<TdApi.UpdateCall>()
    .mapNotNull { it.call }

/**
 * emits [GroupCall] if information about a group call was updated.
 */
fun TelegramFlow.groupCallFlow(): Flow<TdApi.GroupCall> =
    this.getUpdatesFlowOfType<TdApi.UpdateGroupCall>()
    .mapNotNull { it.groupCall }

/**
 * emits [UpdateGroupCallParticipant] if information about a group call participant was changed. The
 * updates are sent only after the group call is received through getGroupCall and only if the call is
 * joined or being joined.
 */
fun TelegramFlow.groupCallParticipantFlow(): Flow<TdApi.UpdateGroupCallParticipant> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewCallSignalingData] if new call signaling data arrived.
 */
fun TelegramFlow.newCallSignalingDataFlow(): Flow<TdApi.UpdateNewCallSignalingData> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewCallbackQuery] if a new incoming callback query; for bots only.
 */
fun TelegramFlow.newCallbackQueryFlow(): Flow<TdApi.UpdateNewCallbackQuery> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewInlineCallbackQuery] if a new incoming callback query from a message sent via a
 * bot; for bots only.
 */
fun TelegramFlow.newInlineCallbackQueryFlow(): Flow<TdApi.UpdateNewInlineCallbackQuery> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewBusinessCallbackQuery] if a new incoming callback query from a business message;
 * for bots only.
 */
fun TelegramFlow.newBusinessCallbackQueryFlow(): Flow<TdApi.UpdateNewBusinessCallbackQuery> =
    this.getUpdatesFlowOfType()
