//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlin.Array
import kotlin.String
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [AuthorizationState] if the user authorization state has changed.
 */
fun TelegramFlow.authorizationStateFlow(): Flow<TdApi.AuthorizationState> =
    this.getUpdatesFlowOfType<TdApi.UpdateAuthorizationState>()
    .mapNotNull { it.authorizationState }

/**
 * emits [UpdateVideoPublished] if an automatically scheduled message with video has been
 * successfully sent after conversion.
 */
fun TelegramFlow.videoPublishedFlow(): Flow<TdApi.UpdateVideoPublished> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateForumTopicInfo] if basic information about a topic in a forum chat was changed.
 */
fun TelegramFlow.forumTopicInfoFlow(): Flow<TdApi.UpdateForumTopicInfo> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateApplicationVerificationRequired] if a request can't be completed unless application
 * verification is performed; for official mobile applications only. The method
 * setApplicationVerificationToken must be called once the verification is completed or failed.
 */
fun TelegramFlow.applicationVerificationRequiredFlow(): Flow<TdApi.UpdateApplicationVerificationRequired>
    = this.getUpdatesFlowOfType()

/**
 * emits [UpdateApplicationRecaptchaVerificationRequired] if a request can't be completed unless
 * reCAPTCHA verification is performed; for official mobile applications only. The method
 * setApplicationVerificationToken must be called once the verification is completed or failed.
 */
fun TelegramFlow.applicationRecaptchaVerificationRequiredFlow():
    Flow<TdApi.UpdateApplicationRecaptchaVerificationRequired> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateOption] if an option changed its value.
 */
fun TelegramFlow.optionFlow(): Flow<TdApi.UpdateOption> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateDefaultBackground] if the default background has changed.
 */
fun TelegramFlow.defaultBackgroundFlow(): Flow<TdApi.UpdateDefaultBackground> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateLanguagePackStrings] if some language pack strings have been updated.
 */
fun TelegramFlow.languagePackStringsFlow(): Flow<TdApi.UpdateLanguagePackStrings> =
    this.getUpdatesFlowOfType()

/**
 * emits state [ConnectionState] if the connection state has changed. This update must be used only
 * to show a human-readable description of the connection state.
 */
fun TelegramFlow.connectionStateFlow(): Flow<TdApi.ConnectionState> =
    this.getUpdatesFlowOfType<TdApi.UpdateConnectionState>()
    .mapNotNull { it.state }

/**
 * emits [UpdateTermsOfService] if new terms of service must be accepted by the user. If the terms
 * of service are declined, then the deleteAccount method must be called with the reason &quot;Decline
 * ToS update&quot;.
 */
fun TelegramFlow.termsOfServiceFlow(): Flow<TdApi.UpdateTermsOfService> = this.getUpdatesFlowOfType()

/**
 * emits session [UnconfirmedSession] if the first unconfirmed session has changed.
 */
fun TelegramFlow.unconfirmedSessionFlow(): Flow<TdApi.UnconfirmedSession> =
    this.getUpdatesFlowOfType<TdApi.UpdateUnconfirmedSession>()
    .mapNotNull { it.session }

/**
 * emits bots [AttachmentMenuBot[]] if the list of bots added to attachment or side menu has
 * changed.
 */
fun TelegramFlow.attachmentMenuBotsFlow(): Flow<Array<TdApi.AttachmentMenuBot>> =
    this.getUpdatesFlowOfType<TdApi.UpdateAttachmentMenuBots>()
    .mapNotNull { it.bots }

/**
 * emits emojis [String[]] if the list of active emoji reactions has changed.
 */
fun TelegramFlow.activeEmojiReactionsFlow(): Flow<Array<String>> =
    this.getUpdatesFlowOfType<TdApi.UpdateActiveEmojiReactions>()
    .mapNotNull { it.emojis }

/**
 * emits [UpdateStarRevenueStatus] if the Telegram Star revenue earned by a bot or a chat has
 * changed. If Telegram Star transaction screen of the chat is opened, then getStarTransactions may be
 * called to fetch new transactions.
 */
fun TelegramFlow.starRevenueStatusFlow(): Flow<TdApi.UpdateStarRevenueStatus> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateSpeechRecognitionTrial] if the parameters of speech recognition without Telegram
 * Premium subscription has changed.
 */
fun TelegramFlow.speechRecognitionTrialFlow(): Flow<TdApi.UpdateSpeechRecognitionTrial> =
    this.getUpdatesFlowOfType()

/**
 * emits emojis [String[]] if the list of supported dice emojis has changed.
 */
fun TelegramFlow.diceEmojisFlow(): Flow<Array<String>> =
    this.getUpdatesFlowOfType<TdApi.UpdateDiceEmojis>()
    .mapNotNull { it.emojis }

/**
 * emits [UpdateSuggestedActions] if the list of suggested to the user actions has changed.
 */
fun TelegramFlow.suggestedActionsFlow(): Flow<TdApi.UpdateSuggestedActions> = this.getUpdatesFlowOfType()

/**
 * emits closeBirthdayUsers [CloseBirthdayUser[]] if the list of contacts that had birthdays
 * recently or will have birthday soon has changed.
 */
fun TelegramFlow.contactCloseBirthdaysFlow(): Flow<Array<TdApi.CloseBirthdayUser>> =
    this.getUpdatesFlowOfType<TdApi.UpdateContactCloseBirthdays>()
    .mapNotNull { it.closeBirthdayUsers }

/**
 * emits [UpdateAutosaveSettings] if autosave settings for some type of chats were updated.
 */
fun TelegramFlow.autosaveSettingsFlow(): Flow<TdApi.UpdateAutosaveSettings> = this.getUpdatesFlowOfType()

/**
 * emits connection [BusinessConnection] if a business connection has changed; for bots only.
 */
fun TelegramFlow.businessConnectionFlow(): Flow<TdApi.BusinessConnection> =
    this.getUpdatesFlowOfType<TdApi.UpdateBusinessConnection>()
    .mapNotNull { it.connection }

/**
 * emits [UpdateNewInlineQuery] if a new incoming inline query; for bots only.
 */
fun TelegramFlow.newInlineQueryFlow(): Flow<TdApi.UpdateNewInlineQuery> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewChosenInlineResult] if the user has chosen a result of an inline query; for bots
 * only.
 */
fun TelegramFlow.newChosenInlineResultFlow(): Flow<TdApi.UpdateNewChosenInlineResult> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewShippingQuery] if a new incoming shipping query; for bots only. Only for invoices
 * with flexible price.
 */
fun TelegramFlow.newShippingQueryFlow(): Flow<TdApi.UpdateNewShippingQuery> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateNewPreCheckoutQuery] if a new incoming pre-checkout query; for bots only. Contains
 * full information about a checkout.
 */
fun TelegramFlow.newPreCheckoutQueryFlow(): Flow<TdApi.UpdateNewPreCheckoutQuery> =
    this.getUpdatesFlowOfType()

/**
 * emits event [String] if a new incoming event; for bots only.
 */
fun TelegramFlow.newCustomEventFlow(): Flow<String> =
    this.getUpdatesFlowOfType<TdApi.UpdateNewCustomEvent>()
    .mapNotNull { it.event }

/**
 * emits [UpdateNewCustomQuery] if a new incoming query; for bots only.
 */
fun TelegramFlow.newCustomQueryFlow(): Flow<TdApi.UpdateNewCustomQuery> = this.getUpdatesFlowOfType()

/**
 * emits [UpdatePaidMediaPurchased] if paid media were purchased by a user; for bots only.
 */
fun TelegramFlow.paidMediaPurchasedFlow(): Flow<TdApi.UpdatePaidMediaPurchased> =
    this.getUpdatesFlowOfType()
