//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlin.Int
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits topicCount [Int] if number of Saved Messages topics has changed.
 */
fun TelegramFlow.savedMessagesTopicCountFlow(): Flow<Int> =
    this.getUpdatesFlowOfType<TdApi.UpdateSavedMessagesTopicCount>()
    .mapNotNull { it.topicCount }

/**
 * emits [UpdateUnreadMessageCount] if number of unread messages in a chat list has changed. This
 * update is sent only if the message database is used.
 */
fun TelegramFlow.unreadMessageCountFlow(): Flow<TdApi.UpdateUnreadMessageCount> =
    this.getUpdatesFlowOfType()

/**
 * emits [StarAmount] if the number of Telegram Stars owned by the current user has changed.
 */
fun TelegramFlow.ownedStarCountFlow(): Flow<TdApi.StarAmount> =
    this.getUpdatesFlowOfType<TdApi.UpdateOwnedStarCount>()
    .mapNotNull { it.starAmount }
