//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlin.Long
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [File] if information about a file was updated.
 */
fun TelegramFlow.fileFlow(): Flow<TdApi.File> = this.getUpdatesFlowOfType<TdApi.UpdateFile>()
    .mapNotNull { it.file }

/**
 * emits [UpdateFileGenerationStart] if the file generation process needs to be started by the
 * application. Use setFileGenerationProgress and finishFileGeneration to generate the file.
 */
fun TelegramFlow.fileGenerationStartFlow(): Flow<TdApi.UpdateFileGenerationStart> =
    this.getUpdatesFlowOfType()

/**
 * emits generationId [Long] if file generation is no longer needed.
 */
fun TelegramFlow.fileGenerationStopFlow(): Flow<Long> =
    this.getUpdatesFlowOfType<TdApi.UpdateFileGenerationStop>()
    .mapNotNull { it.generationId }

/**
 * emits [UpdateFileDownloads] if the state of the file download list has changed.
 */
fun TelegramFlow.fileDownloadsFlow(): Flow<TdApi.UpdateFileDownloads> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateFileAddedToDownloads] if a file was added to the file download list. This update is
 * sent only after file download list is loaded for the first time.
 */
fun TelegramFlow.fileAddedToDownloadsFlow(): Flow<TdApi.UpdateFileAddedToDownloads> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateFileDownload] if a file download was changed. This update is sent only after file
 * download list is loaded for the first time.
 */
fun TelegramFlow.fileDownloadFlow(): Flow<TdApi.UpdateFileDownload> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateFileRemovedFromDownloads] if a file was removed from the file download list. This
 * update is sent only after file download list is loaded for the first time.
 */
fun TelegramFlow.fileRemovedFromDownloadsFlow(): Flow<TdApi.UpdateFileRemovedFromDownloads> =
    this.getUpdatesFlowOfType()
