//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi.Poll
import org.drinkless.tdlib.TdApi.UpdatePoll
import org.drinkless.tdlib.TdApi.UpdatePollAnswer

/**
 * emits [Poll] if a poll was updated; for bots only.
 */
fun TelegramFlow.pollFlow(): Flow<Poll> = this.getUpdatesFlowOfType<UpdatePoll>()
    .mapNotNull { it.poll }

/**
 * emits [UpdatePollAnswer] if a user changed the answer to a poll; for bots only.
 */
fun TelegramFlow.pollAnswerFlow(): Flow<UpdatePollAnswer> = this.getUpdatesFlowOfType()
