//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [ReactionType] if the type of default reaction has changed.
 */
fun TelegramFlow.defaultReactionTypeFlow(): Flow<TdApi.ReactionType> =
    this.getUpdatesFlowOfType<TdApi.UpdateDefaultReactionType>()
    .mapNotNull { it.reactionType }

/**
 * emits type [PaidReactionType] if the type of default paid reaction has changed.
 */
fun TelegramFlow.defaultPaidReactionTypeFlow(): Flow<TdApi.PaidReactionType> =
    this.getUpdatesFlowOfType<TdApi.UpdateDefaultPaidReactionType>()
    .mapNotNull { it.type }
