//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlin.IntArray
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [StickerSet] if a sticker set has changed.
 */
fun TelegramFlow.stickerSetFlow(): Flow<TdApi.StickerSet> =
    this.getUpdatesFlowOfType<TdApi.UpdateStickerSet>()
    .mapNotNull { it.stickerSet }

/**
 * emits [UpdateInstalledStickerSets] if the list of installed sticker sets was updated.
 */
fun TelegramFlow.installedStickerSetsFlow(): Flow<TdApi.UpdateInstalledStickerSets> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateTrendingStickerSets] if the list of trending sticker sets was updated or some of
 * them were viewed.
 */
fun TelegramFlow.trendingStickerSetsFlow(): Flow<TdApi.UpdateTrendingStickerSets> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateRecentStickers] if the list of recently used stickers was updated.
 */
fun TelegramFlow.recentStickersFlow(): Flow<TdApi.UpdateRecentStickers> = this.getUpdatesFlowOfType()

/**
 * emits stickerIds [Int[]] if the list of favorite stickers was updated.
 */
fun TelegramFlow.favoriteStickersFlow(): Flow<IntArray> =
    this.getUpdatesFlowOfType<TdApi.UpdateFavoriteStickers>()
    .mapNotNull { it.stickerIds }
