//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [Story] if a story was changed.
 */
fun TelegramFlow.storyFlow(): Flow<TdApi.Story> = this.getUpdatesFlowOfType<TdApi.UpdateStory>()
    .mapNotNull { it.story }

/**
 * emits [UpdateStoryDeleted] if a story became inaccessible.
 */
fun TelegramFlow.storyDeletedFlow(): Flow<TdApi.UpdateStoryDeleted> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateStorySendSucceeded] if a story has been successfully sent.
 */
fun TelegramFlow.storySendSucceededFlow(): Flow<TdApi.UpdateStorySendSucceeded> =
    this.getUpdatesFlowOfType()

/**
 * emits [UpdateStorySendFailed] if a story failed to send. If the story sending is canceled, then
 * updateStoryDeleted will be received instead of this update.
 */
fun TelegramFlow.storySendFailedFlow(): Flow<TdApi.UpdateStorySendFailed> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateStoryStealthMode] if story stealth mode settings have changed.
 */
fun TelegramFlow.storyStealthModeFlow(): Flow<TdApi.UpdateStoryStealthMode> = this.getUpdatesFlowOfType()
