//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [Supergroup] if some data of a supergroup or a channel has changed. This update is
 * guaranteed to come before the supergroup identifier is returned to the application.
 */
fun TelegramFlow.supergroupFlow(): Flow<TdApi.Supergroup> =
    this.getUpdatesFlowOfType<TdApi.UpdateSupergroup>()
    .mapNotNull { it.supergroup }

/**
 * emits [UpdateSupergroupFullInfo] if some data in supergroupFullInfo has been changed.
 */
fun TelegramFlow.supergroupFullInfoFlow(): Flow<TdApi.UpdateSupergroupFullInfo> =
    this.getUpdatesFlowOfType()
