//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.flows

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import org.drinkless.tdlib.TdApi

/**
 * emits [UpdateUserStatus] if the user went online or offline.
 */
fun TelegramFlow.userStatusFlow(): Flow<TdApi.UpdateUserStatus> = this.getUpdatesFlowOfType()

/**
 * emits [User] if some data of a user has changed. This update is guaranteed to come before the
 * user identifier is returned to the application.
 */
fun TelegramFlow.userFlow(): Flow<TdApi.User> = this.getUpdatesFlowOfType<TdApi.UpdateUser>()
    .mapNotNull { it.user }

/**
 * emits [UpdateUserFullInfo] if some data in userFullInfo has been changed.
 */
fun TelegramFlow.userFullInfoFlow(): Flow<TdApi.UpdateUserFullInfo> = this.getUpdatesFlowOfType()

/**
 * emits [UpdateUserPrivacySettingRules] if some privacy setting rules have been changed.
 */
fun TelegramFlow.userPrivacySettingRulesFlow(): Flow<TdApi.UpdateUserPrivacySettingRules> =
    this.getUpdatesFlowOfType()
