//
// NOTE: THIS FILE IS AUTO-GENERATED by the "ExtensionsGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.extensions

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow
import com.xxcactussell.mategram.kotlinx.telegram.extensions.BaseKtx
import com.xxcactussell.mategram.kotlinx.telegram.coroutines.getSavedNotificationSound
import com.xxcactussell.mategram.kotlinx.telegram.coroutines.removeSavedNotificationSound
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.NotificationSound

/**
 * Interface for access [TdApi.NotificationSound] extension functions. Can be used alongside with
 * other extension interfaces of the package. Must contain [TelegramFlow] instance field to access its
 * functionality
 */
interface NotificationSoundKtx : BaseKtx {
  /**
   * Instance of the [TelegramFlow] connecting extensions to the Telegram Client
   */
  override val api: TelegramFlow

  /**
   * Suspend function, which returns saved notification sound by its identifier. Returns a 404 error
   * if there is no saved notification sound with the specified identifier.
   *
   *
   * @return [TdApi.NotificationSounds] Contains a list of notification sounds.
   */
  suspend fun NotificationSound.getSaved() = api.getSavedNotificationSound(this.id)

  /**
   * Suspend function, which removes a notification sound from the list of saved notification
   * sounds.
   */
  suspend fun NotificationSound.removeSaved() = api.removeSavedNotificationSound(this.id)
}
