//
// NOTE: THIS FILE IS AUTO-GENERATED by the "ExtensionsGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package com.xxcactussell.mategram.kotlinx.telegram.extensions

import com.xxcactussell.mategram.kotlinx.telegram.core.TelegramFlow

/**
 * Interface for access all Telegram objects extension functions. Contains 454 extensions
 */
interface TelegramKtx : AccentColorKtx, BasicGroupKtx, BusinessConnectionKtx, CallKtx, ChatKtx,
    FileKtx, GiftKtx, GroupCallKtx, MessageKtx, NotificationGroupKtx, NotificationSoundKtx,
    ProfileAccentColorKtx, ProxyKtx, SavedMessagesTopicKtx, SecretChatKtx, SessionKtx, StoryKtx,
    SupergroupKtx, UserKtx, CommonKtx {
  /**
   * Instance of the [TelegramFlow] connecting extensions to the Telegram Client
   */
  override val api: TelegramFlow
}
